server:
  port: 8081
  
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/microservices
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 application:
   name: USER_SERVICE
  
 jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect
 
eureka:
 instance:
  prefer-ip-address: true
 client:
  register-with-eureka: true
  fetch-registory: true
  service-url:
   defaultZone: http://localhost:8080/eureka